CREATE TABLE professores
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(64) NOT NULL,
    sobrenome VARCHAR2(64) NOT NULL,
    endereço VARCHAR2(64) NOT NULL,
    telefone VARCHAR2(14) NOT NULL,
    email VARCHAR2(64) NOT NULL,
    datanasc DATE NOT NULL,
    nascionalidade VARCHAR2(64) NOT NULL,
    PRIMARY KEY (id)
)

CREATE TABLE alunos
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(64) NOT NULL,
    sobrenome VARCHAR2(64) NOT NULL,
    matricula VARCHAR2(64) NOT NULL,
    telefone VARCHAR2(14) NOT NULL,
    email VARCHAR2(64) NOT NULL,
    datanasc DATE NOT NULL,
    nascionalidade VARCHAR2(64) NOT NULL,
    mediageral VARCHAR2(4) NOT NULL,
    PRIMARY KEY (id)
)

CREATE TABLE cursos
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR2(64) NOT NULL,
    nome VARCHAR2(64) NOT NULL,
    tipo NUMBER NOT NULL,
    num_alunos NUMBER NOT NULL,
    id_professor NUMBER NOT NULL,
    FOREIGN KEY (id_professor) REFERENCES professor (id)

)

